linters:
  enable:
    - revive
    - gofmt
    - govet

linters-settings:
  revive:
    rules:
      - name: exported
        argument: "The comment should start with the name of the exported declaration"
      - name: comment-spacings # Enforces space after //
