linters:
  enable:
    - revive
    - gofmt
    - govet

linters-settings:
  revive:
    rules:
      - name: exported
        arguments:
          - disableStuttering: true
      - name: comment-spacings # Enforces space after //
