@startuml init
title Command: kitkat init
skinparam style strictuml
start
:User runs `kitkat init`;

partition "Directory Setup" {
  :Create .kitkat/;
  :Create .kitkat/objects/;
  :Create .kitkat/refs/heads/;
  :Create .kitkat/refs/tags/;
}

partition "File Initialization" {
  :Create empty .kitkat/index;
  :Create empty .kitkat/commits.log;
}

partition "HEAD Setup" {
  :Write "ref: refs/heads/main";
  :Save to .kitkat/HEAD;
}

:Print "Initialized empty KitKat repository";
stop
@enduml